test: fixing a bug where calling trash command outside a tagsistant mount deletes the folder from which tagsistant-tools was called

diff --git a/command/.tagsistant-command.d/trash b/command/.tagsistant-command.d/trash
--- a/command/.tagsistant-command.d/trash
+++ b/command/.tagsistant-command.d/trash
@@ -3,13 +3,18 @@
  
 if [ $# -eq 0 ] 
 then 
-     echo "usage rm <file>*"
+     echo "usage trash <file>*"
      exit
 fi
 
 # get mount point
 directoryName=`dirname $0`
 mountPoint=`${directoryName}/root`
+
+if [ $? -ne 0 ]; then
+    echo "invalid mountpoint"
+    exit 1
+fi
 
 # get files to remove
 files=$@
