give support to the rename, tag, tags and untag commands to operate also when calling tagsistant-tools from outside tagsistant mount

diff --git a/command/.tagsistant-command.d/untag b/command/.tagsistant-command.d/untag
--- a/command/.tagsistant-command.d/untag
+++ b/command/.tagsistant-command.d/untag
@@ -11,6 +11,11 @@ fi
 directoryName=`dirname $0`
 mountPoint=`${directoryName}/root $1`
 
+if [ $? -ne 0 ]; then
+    echo "invalid mountpoint"
+    exit 1
+fi
+
 # get file and tag
 files=""
 tags=""
